# Generated by Django 4.2.1 on 2023-05-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_alter_orderentry_options_alter_service_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='engine',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='engine'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='year'),
        ),
    ]
