# Generated by Django 4.2.1 on 2023-05-30 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_carmodel_engine_carmodel_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='garage.carmodel', verbose_name='car model'),
        ),
    ]
