# Generated by Django 4.2.1 on 2023-05-31 05:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0004_alter_car_car_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_back', models.DateField(blank=True, db_index=True, null=True, verbose_name='due back')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'In a Row'), (1, 'Working'), (2, 'Pending'), (3, 'Done'), (4, 'Canceled')], db_index=True, default=0, verbose_name='status')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='garage.orderentry', verbose_name='')),
            ],
            options={
                'verbose_name': 'order instance',
                'verbose_name_plural': 'order instances',
                'ordering': ['due_back'],
            },
        ),
    ]
