# Generated by Django 4.2.1 on 2023-05-31 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_orderinstance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderInstance',
        ),
    ]
