# Generated by Django 4.2.1 on 2023-05-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0007_alter_order_amount_alter_orderentry_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'In a Row'), (1, 'Working'), (2, 'Pending'), (3, 'Done'), (7, 'Cancelled')], db_index=True, default=0, verbose_name='status'),
        ),
    ]
