# Generated by Django 4.2.1 on 2023-06-01 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0008_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orderentry',
            name='price',
        ),
    ]
