# Generated by Django 4.2.1 on 2023-06-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0009_remove_order_amount_remove_orderentry_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='garage/car_covers', verbose_name='cover'),
        ),
    ]
