# Generated by Django 4.2.1 on 2023-06-06 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0010_car_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='client',
        ),
    ]
