# Generated by Django 4.2.1 on 2023-06-06 09:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0013_order_due_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='notes',
            field=tinymce.models.HTMLField(blank=True, max_length=8000, null=True, verbose_name='client'),
        ),
    ]
