# Generated by Django 4.2.1 on 2023-06-07 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garage', '0014_car_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='notes',
            field=tinymce.models.HTMLField(blank=True, max_length=8000, null=True, verbose_name='notes'),
        ),
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Reviewed')),
                ('content', models.TextField(max_length=4000, verbose_name='content')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='garage.order', verbose_name='order')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_reviews', to=settings.AUTH_USER_MODEL, verbose_name='reviewer')),
            ],
            options={
                'verbose_name': 'order review',
                'verbose_name_plural': 'order reviews',
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
